# This is a basic workflow to help you get started with Actions
name: CI/CD terraform AWS
# Controls when the workflow will run
on: workflow_dispatch
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions/init@v0.4.0

      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions/validate@v0.3.7
      
      - name: Terraform Apply
        #uses: hashicorp/terraform-github-actions/apply@v0.4.0
        uses: kciter/terraform-apply-for-aws-action@v3
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #auto_approve: true
          #aws-region: 'us-east-1'

   
