name: Add File to Bucket
on: push

jobs:
  upload:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@master
   
      - name: Upload file to bucket
        uses: zdurham/s3-upload-github-action@master
        with:
          #args: --acl public-read
          FILE: ./main.tf
          AWS_REGION: 'eu-north-1'
          S3_BUCKET: 'test-github-action-demo-bucket'
          #S3_KEY: ${{ secrets.S3_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
